name: bond_cli
description: A CLI tool for efficient Flutter Bond app development, streamlining tasks like project setup and package management.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.3

dependencies:
  args: ^2.4.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

#  generate a description for bond_cli executable package