name: bond_cli
description: A CLI tool for efficient Flutter Bond app development, streamlining tasks like project setup and package management.
version: 0.0.2
repository: https://github.com/onestudio-co/bond-cli

environment:
  sdk: ^3.0.3

dependencies:
  interact: ^2.2.0
  args: ^2.4.2
  native_project_manipulator: ^0.0.9
  meta: ^1.9.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

executables:
  bond: